# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "375e36f1941551d648b389d408b06d6b"
name = "Leopard Booking"
application_url = "https://book-with-leopards.vercel.app"
embedded = true
handle = "leopard-booking-1"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/gdpr/webhooks/customers_data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/gdpr/webhooks/customers_redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/fulfillments/create"
  topics = [ "fulfillments/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/fulfillments/update"
  topics = [ "fulfillments/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/delete"
  topics = [ "orders/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/fulfilled"
  topics = [ "orders/fulfilled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/updated"
  topics = [ "orders/updated" ]

[access_scopes]
scopes = "read_orders,write_orders,read_products,read_customers,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_locations"

[auth]
redirect_urls = [
  "https://book-with-leopards.vercel.app/auth/callback",
  "https://book-with-leopards.vercel.app/auth/shopify/callback",
  "https://book-with-leopards.vercel.app/api/auth/callback"
]
